const DB_NAME='ofp-db',DB_VER=1;let db,exercises=[],programs=[],measurements=[],logs=[],rituals=[],schedules=[],calendarCursor=new Date(),selectedDate='',activeProgram=null,timerInt=null;calendarCursor.setDate(1);
const $=id=>document.getElementById(id),uid=(p='id')=>p+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),isoDate=(d=new Date())=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)},esc=s=>(s??'').toString().replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));selectedDate=isoDate();
function dbOpen(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{const d=r.result;['exercises','programs','measurements','logs','rituals','schedule','meta'].forEach(s=>{if(!d.objectStoreNames.contains(s))d.createObjectStore(s,{keyPath:'id'})})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function dbPut(s,o){return new Promise((res,rej)=>{const t=db.transaction(s,'readwrite');t.objectStore(s).put(o);t.oncomplete=()=>res(o);t.onerror=()=>rej(t.error)})}function dbGetAll(s){return new Promise((res,rej)=>{const r=db.transaction(s).objectStore(s).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function dbDelete(s,id){return new Promise((res,rej)=>{const t=db.transaction(s,'readwrite');t.objectStore(s).delete(id);t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}function dbClear(s){return new Promise((res,rej)=>{const t=db.transaction(s,'readwrite');t.objectStore(s).clear();t.oncomplete=()=>res();t.onerror=()=>rej(t.error)})}
const morning=[['Ходьба на месте + свободные руки','60 сек'],['Плечи + повороты корпуса','60 сек'],['Приседания','10–15'],['Отжимания','5–10, с запасом'],['Выпады назад','5/сторона'],['Bird-dog','6–8/сторона'],['Планка','15–30 сек'],['Энергичная ходьба','60–90 сек'],['Потянуться + спокойное дыхание','30–60 сек']];
const mobility=[['Шея','30–40 сек'],['Плечи и лопатки','10 кругов'],['Руки над головой','8–10'],['Грудной отдел','8/сторона'],['Таз','8–10 кругов'],['Тазобедренные','6–8/нога'],['Выпад + вытяжение','5/сторона'],['Голеностоп','10–15/нога'],['Спокойный присед','8–10'],['Финишное вытяжение','30–60 сек']];
const builtinExercises=[
{id:'ex-squat',name:'Приседание',category:'Сила',desc:'Базовое упражнение на ноги.',tech:'Стопы устойчивы, колени идут по направлению носков, пятки на полу, корпус под контролем.',sets:2,reps:'12',rest:60,builtin:true},
{id:'ex-push',name:'Отжимание',category:'Сила',desc:'Жим собственным весом.',tech:'Корпус единым блоком. Остановиться до провисания таза и потери амплитуды.',sets:3,reps:'8–10',rest:90,builtin:true},
{id:'ex-lunge',name:'Выпад назад',category:'Сила',desc:'Ноги, баланс и контроль таза.',tech:'Шаг назад, переднее колено следует направлению стопы, корпус собран.',sets:2,reps:'8/сторона',rest:60,builtin:true},
{id:'ex-birddog',name:'Bird-dog',category:'Кор',desc:'Стабилизация корпуса и координация.',tech:'На четвереньках вытянуть противоположные руку и ногу, таз не разворачивать.',sets:2,reps:'6/сторона',rest:45,builtin:true},
{id:'ex-sideplank',name:'Боковая планка',category:'Кор',desc:'Антинаклон и боковая стабильность.',tech:'Локоть под плечом, таз поднят, тело одной линией.',sets:2,reps:'15–25 сек/сторона',rest:45,builtin:true},
{id:'ex-deadbug',name:'Dead bug',category:'Кор',desc:'Контроль корпуса лёжа.',tech:'Поясница мягко прижата, противоположные рука и нога опускаются медленно.',sets:2,reps:'6–8/сторона',rest:45,builtin:true},
{id:'ex-walk',name:'Быстрая ходьба / марш',category:'Кардио',desc:'Лёгкая аэробная работа.',tech:'Разговорный темп, без перехода в тяжёлую одышку.',sets:1,reps:'6–10 мин',rest:0,builtin:true}
];
const defaultPrograms=[{id:'pr-a',name:'ОФП A · старт',desc:'Базовая силовая + кор + лёгкое кардио',exerciseIds:['ex-squat','ex-push','ex-lunge','ex-birddog','ex-sideplank','ex-walk'],builtin:true}];
const defaultRituals=[{id:'rit-charge',name:'Утренняя зарядка',mode:'time',time:'08:00',interval:0,lastDone:null,builtin:true},{id:'rit-mobile',name:'Мобильность',mode:'interval',time:'',interval:3,lastDone:null,builtin:true}];
function openTab(id){document.querySelectorAll('section').forEach(s=>s.classList.remove('on'));$(id).classList.add('on');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('on',b.dataset.tab===id));if(id==='calendar')renderCalendar()}function openPassport(){openTab('passport');renderPassport()}document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));
function showModal(id){$(id).classList.add('on')}function hideModal(id){$(id).classList.remove('on')}function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('ofp-theme',t);document.querySelectorAll('[data-themebtn]').forEach(b=>b.classList.toggle('on',b.dataset.themebtn===t))}function setCycle(v){localStorage.setItem('ofp-cycle',v);renderHome()}
function renderChecklist(rootId,data,prefix){const root=$(rootId),day=isoDate();root.innerHTML=data.map((x,i)=>{const key=`ofp-check-${day}-${prefix}-${i}`,c=localStorage.getItem(key)==='1';return `<div class="item ${c?'done':''}"><label class="check"><input type="checkbox" ${c?'checked':''} onchange="localStorage.setItem('${key}',this.checked?'1':'0');this.closest('.item').classList.toggle('done',this.checked);renderHome()"><div><b>${esc(x[0])}</b><div class="small">${esc(x[1])}</div></div></label></div>`}).join('')}
async function seed(){exercises=await dbGetAll('exercises');if(!exercises.length){for(const x of builtinExercises)await dbPut('exercises',x)}programs=await dbGetAll('programs');if(!programs.length){for(const x of defaultPrograms)await dbPut('programs',x)}rituals=await dbGetAll('rituals');if(!rituals.length){for(const x of defaultRituals)await dbPut('rituals',x)}const old=localStorage.getItem('ofp-v021');if(old&&!localStorage.getItem('ofp-migrated-v021')){try{const s=JSON.parse(old);for(const m of s.metrics||[])await dbPut('measurements',{id:uid('m'),date:m.date||isoDate(),ts:new Date().toISOString(),weight:Number(m.weight||0),waist:Number(m.waist||0),pulse:Number(m.pulse||0),push:Number(m.pushups||m.push||0),plank:Number(m.plank||0),pull:Number(m.pullups||m.pull||0)});for(const l of s.logs||[])await dbPut('logs',{id:uid('log'),date:l.date||isoDate(),ts:new Date().toISOString(),programName:'Импорт из v0.2.1',doneExerciseIds:[],total:0,note:l.note||'',sleep:l.sleep||'',feel:l.feel||'',rpe:l.rpe||''});if(s.cycle)localStorage.setItem('ofp-cycle',s.cycle);localStorage.setItem('ofp-migrated-v021','1')}catch(e){}}}
async function refresh(){exercises=await dbGetAll('exercises');programs=await dbGetAll('programs');measurements=await dbGetAll('measurements');logs=await dbGetAll('logs');rituals=await dbGetAll('rituals');schedules=await dbGetAll('schedule');renderAll()}
function renderAll(){renderChecklist('morningList',morning,'morning');renderChecklist('mobilityList',mobility,'mob');renderExercises();renderPrograms();renderRituals();renderProgress();renderPassport();renderHome();renderSettings();renderCalendar()}
function tick(){const n=new Date();$('clock').textContent=n.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});$('dateNow').textContent=n.toLocaleDateString('ru-RU',{weekday:'short',day:'numeric',month:'short'});renderHome()}
function ritualDue(r){const now=new Date();if(r.mode==='time'){const [h,m]=(r.time||'09:00').split(':').map(Number),due=new Date();due.setHours(h,m,0,0);const done=r.lastDone&&isoDate(new Date(r.lastDone))===isoDate();return !done&&now>=due}if(r.mode==='interval'){if(!r.lastDone)return true;return now-new Date(r.lastDone)>=Number(r.interval||3)*3600000}return false}
function nextRitualText(r){if(ritualDue(r))return'пора';if(r.mode==='time')return`сегодня ${r.time}`;if(!r.lastDone)return'можно выполнить';const due=new Date(new Date(r.lastDone).getTime()+Number(r.interval||3)*3600000);return`следующее ≈ ${due.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}`}
function renderHome(){const cycle=localStorage.getItem('ofp-cycle')||'duty',map={duty:'Рабочие сутки: основная цель — движение, мобильность и прогулка. Полная тренировка не обязательна.',recovery:'После смены: восстановление, сон/отдых, прогулка и мягкая мобильность.',a:'Полный выходной A: основной тренировочный день.',b:'Полный выходной B: умеренная вторая тренировка / техника / аэробная работа.'},labels={duty:'Сутки',recovery:'После смены',a:'Выходной A',b:'Выходной B'};$('todayBadge').textContent=labels[cycle];$('todaySummary').textContent=map[cycle];const due=rituals.filter(ritualDue);$('dueRituals').innerHTML=due.length?due.map(r=>`<div class="item"><div class="row between"><div><b>${esc(r.name)}</b><div class="small">${nextRitualText(r)}</div></div><button class="btn" onclick="completeRitual('${r.id}')">Готово</button></div></div>`).join(''):'<div class="small">Срочных ритуалов сейчас нет.</div>'}
async function completeRitual(id){const r=rituals.find(x=>x.id===id);if(!r)return;r.lastDone=new Date().toISOString();await dbPut('rituals',r);await refresh()}
function renderRituals(){$('ritualList').innerHTML=rituals.length?rituals.map(r=>`<div class="item"><div class="row between"><div><b>${esc(r.name)}</b><div class="small">${r.mode==='time'?`ежедневно в ${esc(r.time)}`:`каждые ${esc(r.interval)} ч после выполнения`} · ${nextRitualText(r)}</div></div><div class="row"><button class="btn secondary" onclick="completeRitual('${r.id}')">✓</button>${!r.builtin?`<button class="btn danger" onclick="deleteRitual('${r.id}')">×</button>`:''}</div></div></div>`).join(''):'<div class="empty">Ритуалов нет.</div>'}
async function saveRitual(){await dbPut('rituals',{id:uid('rit'),name:$('ritName').value.trim()||'Ритуал',mode:$('ritMode').value,time:$('ritTime').value,interval:Number($('ritInterval').value||3),lastDone:null,builtin:false});hideModal('ritualModal');$('ritName').value='';await refresh()}async function deleteRitual(id){await dbDelete('rituals',id);await refresh()}
function mediaUrl(ex){return ex.mediaBlob?URL.createObjectURL(ex.mediaBlob):null}
function renderExercises(){$('exerciseList').innerHTML=exercises.length?[...exercises].sort((a,b)=>a.name.localeCompare(b.name,'ru')).map(ex=>{const url=mediaUrl(ex);return `<div class="item"><div class="row between"><div><b>${esc(ex.name)}</b><div class="small">${esc(ex.category)} · ${esc(ex.sets)} × ${esc(ex.reps)} · отдых ${esc(ex.rest)} сек</div></div><span class="tag">${ex.builtin?'встроенное':'моё'}</span></div>${url?`<img class="exercise-media" src="${url}">`:''}${ex.desc?`<div style="margin-top:7px">${esc(ex.desc)}</div>`:''}${ex.tech?`<div class="small" style="margin-top:5px"><b>Техника:</b> ${esc(ex.tech)}</div>`:''}${!ex.builtin?`<div class="row" style="margin-top:8px"><button class="btn secondary" onclick="editExercise('${ex.id}')">Изменить</button><button class="btn danger" onclick="removeExercise('${ex.id}')">Удалить</button></div>`:''}</div>`}).join(''):'<div class="empty">Библиотека пуста.</div>'}
function openExerciseEditor(){$('exId').value='';$('exName').value='';$('exCat').value='Сила';$('exDesc').value='';$('exTech').value='';$('exSets').value=2;$('exReps').value='8–10';$('exRest').value=60;$('exMedia').value='';$('exMediaPreview').innerHTML='';showModal('exerciseModal')}
function editExercise(id){const ex=exercises.find(x=>x.id===id);if(!ex)return;$('exId').value=ex.id;$('exName').value=ex.name;$('exCat').value=ex.category;$('exDesc').value=ex.desc||'';$('exTech').value=ex.tech||'';$('exSets').value=ex.sets||2;$('exReps').value=ex.reps||'';$('exRest').value=ex.rest||60;$('exMediaPreview').innerHTML=ex.mediaBlob?`<img class="exercise-media" src="${URL.createObjectURL(ex.mediaBlob)}">`:'';showModal('exerciseModal')}
async function saveExercise(){const old=exercises.find(x=>x.id===$('exId').value),f=$('exMedia').files[0],obj={id:$('exId').value||uid('ex'),name:$('exName').value.trim()||'Без названия',category:$('exCat').value,desc:$('exDesc').value.trim(),tech:$('exTech').value.trim(),sets:Number($('exSets').value||1),reps:$('exReps').value.trim(),rest:Number($('exRest').value||0),builtin:false,mediaBlob:f||old?.mediaBlob||null,mediaName:f?.name||old?.mediaName||null};await dbPut('exercises',obj);hideModal('exerciseModal');await refresh()}
async function removeExercise(id){if(programs.some(p=>(p.exerciseIds||[]).includes(id))){alert('Упражнение используется в сохранённой программе. Сначала убери его из программы.');return}await dbDelete('exercises',id);await refresh()}
function renderPrograms(){$('programList').innerHTML=programs.length?programs.map(p=>`<div class="item"><div class="row between"><div><b>${esc(p.name)}</b><div class="small">${esc(p.desc||'')} · ${(p.exerciseIds||[]).length} упражнений</div></div><span class="tag">${p.builtin?'встроенная':'моя'}</span></div><div class="row" style="margin-top:8px"><button class="btn" onclick="runProgram('${p.id}')">Запустить</button>${!p.builtin?`<button class="btn secondary" onclick="editProgram('${p.id}')">Изменить</button><button class="btn secondary" onclick="duplicateProgram('${p.id}')">Копия</button><button class="btn danger" onclick="removeProgram('${p.id}')">Удалить</button>`:''}</div></div>`).join(''):'<div class="empty">Сохранённых программ нет.</div>'}
function buildProgramPicker(selected=[]){$('programExercisePicker').innerHTML=exercises.map(ex=>`<div class="item"><label class="check"><input type="checkbox" value="${ex.id}" ${selected.includes(ex.id)?'checked':''}><div><b>${esc(ex.name)}</b><div class="small">${esc(ex.category)} · ${esc(ex.sets)} × ${esc(ex.reps)}</div></div></label></div>`).join('')}
function openProgramEditor(){$('prId').value='';$('prName').value='';$('prDesc').value='';buildProgramPicker([]);showModal('programModal')}function editProgram(id){const p=programs.find(x=>x.id===id);if(!p)return;$('prId').value=p.id;$('prName').value=p.name;$('prDesc').value=p.desc||'';buildProgramPicker(p.exerciseIds||[]);showModal('programModal')}
async function saveProgram(){const selected=[...$('programExercisePicker').querySelectorAll('input:checked')].map(x=>x.value);await dbPut('programs',{id:$('prId').value||uid('pr'),name:$('prName').value.trim()||'Моя программа',desc:$('prDesc').value.trim(),exerciseIds:selected,builtin:false});hideModal('programModal');await refresh()}async function duplicateProgram(id){const p=programs.find(x=>x.id===id);if(!p)return;await dbPut('programs',{...p,id:uid('pr'),name:p.name+' · копия',builtin:false});await refresh()}async function removeProgram(id){await dbDelete('programs',id);await refresh()}
function runProgram(id){activeProgram=programs.find(x=>x.id===id);if(!activeProgram)return;$('runTitle').textContent=activeProgram.name;$('runCard').style.display='block';$('runList').innerHTML=(activeProgram.exerciseIds||[]).map((eid,i)=>{const ex=exercises.find(x=>x.id===eid);if(!ex)return'';return `<div class="item"><label class="check"><input type="checkbox" data-run="${eid}"><div><b>${i+1}. ${esc(ex.name)}</b><div class="small">${esc(ex.sets)} × ${esc(ex.reps)} · отдых ${esc(ex.rest)} сек</div><div>${esc(ex.tech||'')}</div></div></label></div>`}).join('');$('runCard').scrollIntoView({behavior:'smooth'})}
function stopProgram(){$('runCard').style.display='none';activeProgram=null;clearInterval(timerInt)}async function finishProgram(){if(!activeProgram)return;const checks=[...$('runList').querySelectorAll('input[data-run]')],done=checks.filter(x=>x.checked).map(x=>x.dataset.run);await dbPut('logs',{id:uid('log'),date:isoDate(),ts:new Date().toISOString(),programId:activeProgram.id,programName:activeProgram.name,doneExerciseIds:done,total:checks.length,note:$('runNote').value.trim()});$('runNote').value='';stopProgram();await refresh();openTab('progress')}
function startTimer(s){clearInterval(timerInt);let n=s;$('timer').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;timerInt=setInterval(()=>{n--;$('timer').textContent=`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;if(n<=0){clearInterval(timerInt);navigator.vibrate&&navigator.vibrate([120,80,120])}},1000)}
async function saveMeasurement(){await dbPut('measurements',{id:uid('m'),date:isoDate(),ts:new Date().toISOString(),weight:Number($('mWeight').value||0),waist:Number($('mWaist').value||0),pulse:Number($('mPulse').value||0),push:Number($('mPush').value||0),plank:Number($('mPlank').value||0),pull:Number($('mPull').value||0)});await refresh()}
function renderProgress(){const ms=[...measurements].sort((a,b)=>(b.ts||'').localeCompare(a.ts||''));$('measureHistory').innerHTML=ms.length?ms.map(x=>`<div class="item"><b>${esc(x.date)}</b><div class="small">Вес ${x.weight||'—'} кг · талия ${x.waist||'—'} см · пульс ${x.pulse||'—'} · отжимания ${x.push||'—'} · планка ${x.plank||'—'} сек · подтягивания ${x.pull||'—'}</div></div>`).join(''):'<div class="empty">Контрольных замеров пока нет.</div>';const ls=[...logs].sort((a,b)=>(b.ts||'').localeCompare(a.ts||''));$('trainingHistory').innerHTML=ls.length?ls.map(x=>`<div class="item"><b>${esc(x.date)} · ${esc(x.programName||'Тренировка')}</b><div class="small">Выполнено ${x.doneExerciseIds?.length||0}/${x.total||0}</div>${x.note?`<div>${esc(x.note)}</div>`:''}</div>`).join(''):'<div class="empty">Журнал пока пуст.</div>'}
function renderPassport(){const latest=[...measurements].sort((a,b)=>(b.ts||'').localeCompare(a.ts||''))[0],v=latest||{weight:97,waist:101,pulse:68,push:18,plank:61,pull:0};$('currentMetrics').innerHTML=`<div class="metric"><span class="small">Вес</span><b>${v.weight||97}</b><span class="small">кг</span></div><div class="metric"><span class="small">Талия</span><b>${v.waist||101}</b><span class="small">см</span></div><div class="metric"><span class="small">Пульс</span><b>${v.pulse||68}</b><span class="small">уд/мин</span></div><div class="metric"><span class="small">Отжимания</span><b>${v.push||18}</b><span class="small">раз</span></div><div class="metric"><span class="small">Планка</span><b>${v.plank||61}</b><span class="small">сек</span></div><div class="metric"><span class="small">Подтягивания</span><b>${v.pull||0}</b><span class="small">раз</span></div>`}
function shiftMonth(delta){calendarCursor.setMonth(calendarCursor.getMonth()+delta);renderCalendar()}function selectDate(d){selectedDate=d;renderCalendar()}function showScheduleModal(){$('schDate').value=selectedDate;$('schProgram').innerHTML='<option value="">Без программы</option>'+programs.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');showModal('scheduleModal')}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$('monthTitle').textContent=calendarCursor.toLocaleDateString('ru-RU',{month:'long',year:'numeric'});const first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate();let cells=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="calhead">${x}</div>`);for(let i=0;i<42;i++){let dayNum,dt,out=false;if(i<start){dayNum=prevDays-start+i+1;dt=new Date(y,m-1,dayNum);out=true}else if(i>=start+days){dayNum=i-start-days+1;dt=new Date(y,m+1,dayNum);out=true}else{dayNum=i-start+1;dt=new Date(y,m,dayNum)}const iso=isoDate(dt),today=iso===isoDate(),sel=iso===selectedDate,hasS=schedules.some(x=>x.date===iso),hasL=logs.some(x=>x.date===iso);cells.push(`<div class="day ${out?'out':''} ${today?'today':''} ${sel?'sel':''}" onclick="selectDate('${iso}')"><b>${dayNum}</b><div>${hasS?'<span class="dot warn"></span>':''}${hasL?'<span class="dot"></span>':''}</div></div>`)}$('calendarGrid').innerHTML=cells.join('');$('selectedDateTitle').textContent=new Date(selectedDate+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'});const ev=schedules.filter(x=>x.date===selectedDate),lg=logs.filter(x=>x.date===selectedDate);$('dayEvents').innerHTML=[...ev.map(x=>`<div class="item"><b>${esc(x.time||'')} ${esc(x.title)}</b><div class="small">${esc(programs.find(p=>p.id===x.programId)?.name||'')}</div><div class="row" style="margin-top:7px">${x.programId?`<button class="btn" onclick="openTab('programs');runProgram('${x.programId}')">Запустить</button>`:''}<button class="btn danger" onclick="deleteSchedule('${x.id}')">Удалить</button></div></div>`),...lg.map(x=>`<div class="item done"><b>✓ ${esc(x.programName||'Тренировка')}</b><div class="small">выполнено ${x.doneExerciseIds?.length||0}/${x.total||0}</div></div>`)].join('')||'<div class="empty">На этот день записей нет.</div>'}
async function saveSchedule(){await dbPut('schedule',{id:uid('sch'),date:$('schDate').value||selectedDate,time:$('schTime').value,title:$('schTitle').value.trim()||'Тренировка',programId:$('schProgram').value});hideModal('scheduleModal');$('schTitle').value='';await refresh()}async function deleteSchedule(id){await dbDelete('schedule',id);await refresh()}
function renderSettings(){$('cycleSelect').value=localStorage.getItem('ofp-cycle')||'duty';document.querySelectorAll('[data-themebtn]').forEach(b=>b.classList.toggle('on',b.dataset.themebtn===document.documentElement.dataset.theme))}
async function exportBackup(){const data={schema:1,exportedAt:new Date().toISOString(),settings:{theme:localStorage.getItem('ofp-theme')||'mrak',cycle:localStorage.getItem('ofp-cycle')||'duty'},exercises:exercises.map(({mediaBlob,...x})=>x),programs,measurements,logs,rituals,schedule:schedules};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`OFP_backup_${isoDate()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
async function importBackup(ev){const f=ev.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());for(const s of ['exercises','programs','measurements','logs','rituals','schedule'])await dbClear(s);for(const x of data.exercises||[])await dbPut('exercises',x);for(const x of data.programs||[])await dbPut('programs',x);for(const x of data.measurements||[])await dbPut('measurements',x);for(const x of data.logs||[])await dbPut('logs',x);for(const x of data.rituals||[])await dbPut('rituals',x);for(const x of data.schedule||[])await dbPut('schedule',x);if(data.settings?.theme)setTheme(data.settings.theme);if(data.settings?.cycle)localStorage.setItem('ofp-cycle',data.settings.cycle);await refresh();alert('Резервная копия восстановлена.')}catch(e){alert('Не удалось импортировать файл: '+e.message)}}
async function init(){document.documentElement.dataset.theme=localStorage.getItem('ofp-theme')||'mrak';await dbOpen();await seed();await refresh();tick();setInterval(tick,30000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}init();
